language: node_js
node_js:
  - "6"
  - "7"
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
  - packages/**/node_modules
env:
  - TEST_DIR=core
  - TEST_DIR=transports
  - TEST_DIR=widget-ci
  - TEST_DIR=widget-gauge
  - TEST_DIR=widget-progress
  - TEST_DIR=widget-statistic
  - TEST_DIR=widget-time
script:
  - lerna run test --scope $TEST_DIR