language: node_js
node_js:
  - "6"
  - "7"
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
  - packages/**/node_modules
env:
  - TEST_DIR=vudash
  - TEST_DIR=@vudash/datasource-rest
  - TEST_DIR=@vudash/datasource-random
  - TEST_DIR=@vudash/datasource-value
  - TEST_DIR=@vudash/datasource-google-sheets
  - TEST_DIR=vudash-widget-ci
  - TEST_DIR=vudash-widget-gauge
  - TEST_DIR=vudash-widget-progress
  - TEST_DIR=vudash-widget-statistic
  - TEST_DIR=vudash-widget-time
script:
  - lerna bootstrap
  - lerna run test --scope $TEST_DIR