language: node_js
node_js:
  - "9"
matrix:
  fast_finish: true
cache:
  directories:
  - ~/.npm
  - node_modules
  - packages/**/node_modules
env:
  matrix:
  - PACKAGE=vudash
  - PACKAGE=@vudash/datasource-rest
  - PACKAGE=@vudash/datasource-random
  - PACKAGE=@vudash/datasource-value
  - PACKAGE=@vudash/datasource-google-sheets
  - PACKAGE=vudash-widget-ci
  - PACKAGE=vudash-widget-gauge
  - PACKAGE=vudash-widget-progress
  - PACKAGE=vudash-widget-statistic
  - PACKAGE=vudash-widget-time
  - PACKAGE=vudash-widget-status
  - PACKAGE=@vudash/widget-chart
script:
  - lerna run lint --scope $TEST_DIR
  - lerna run test --scope $TEST_DIR