language: node_js
node_js:
  - "6"
  - "7"
cache:
  directories:
  - node_modules
  - packages/**/node_modules
env:
  - TEST_DIR=packages/core
  - TEST_DIR=packages/transports
  - TEST_DIR=packages/widget-ci
  - TEST_DIR=packages/widget-gauge
  - TEST_DIR=packages/widget-progress
  - TEST_DIR=packages/widget-statistic
  - TEST_DIR=packages/widget-time